# Generated by Django 4.2.4 on 2023-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
